export const aliens = [
    {"alienId":"1","alienName":"Zarnok Beetle","alienLifespan":"3","alienDiet":"Metallic minerals","alienDescription":"A tiny insect from planet Ferros that consumes iron filings and glows neon blue.","alienImage":"../img/alienImgs/a1.webp","alienSound":"../sound/1.wav"},
    {"alienId":"2","alienName":"Glimmerfang","alienLifespan":"12","alienDiet":"Plasma bursts","alienDescription":"A feline-like predator with shimmering fur and razor-sharp plasma teeth.","alienImage":"../img/alienImgs/a2.webp","alienSound":"../sound/2.wav"},
    {"alienId":"3","alienName":"Tharnox","alienLifespan":"200","alienDiet":"Solar radiation","alienDescription":"A massive, slow-moving creature that absorbs sunlight through crystalline plates.","alienImage":"../img/alienImgs/a3.webp","alienSound":"../sound/3.wav"},
    {"alienId":"4","alienName":"Murkflap","alienLifespan":"8","alienDiet":"Swamp gas","alienDescription":"Bat-like alien with translucent wings that thrives in methane-rich bogs.","alienImage":"../img/alienImgs/a4.webp","alienSound":"../sound/4.wav"},
    {"alienId":"5","alienName":"Velvith Serpent","alienLifespan":"40","alienDiet":"Electric eels","alienDescription":"A serpentine hunter that uses bioelectric pulses to stun prey.","alienImage":"../img/alienImgs/a5.webp","alienSound":"../sound/5.wav"},
    {"alienId":"6","alienName":"Orbuloid","alienLifespan":"15","alienDiet":"Floating spores","alienDescription":"A levitating orb-shaped creature that drifts through alien forests consuming airborne spores.","alienImage":"../img/alienImgs/a6.webp","alienSound":"../sound/6.wav"},
    {"alienId":"7","alienName":"Craghopper","alienLifespan":"25","alienDiet":"Rock lichen","alienDescription":"A sturdy quadruped with stone-like skin that grazes on cliffside vegetation.","alienImage":"../img/alienImgs/a7.webp","alienSound":"../sound/7.wav"},
    {"alienId":"8","alienName":"Nimbari","alienLifespan":"60","alienDiet":"Atmospheric ions","alienDescription":"A jellyfish-like being that floats in the upper atmosphere feeding on charged particles.","alienImage":"../img/alienImgs/a8.webp","alienSound":"../sound/8.wav"},
    {"alienId":"9","alienName":"Skreevok","alienLifespan":"5","alienDiet":"Other alien animals","alienDescription":"A hyper-aggressive predator with multiple eyes and sonic screech attacks.","alienImage":"../img/alienImgs/a9.webp","alienSound":"../sound/9.wav"},
    {"alienId":"10","alienName":"Lumipod","alienLifespan":"10","alienDiet":"Bioluminescent algae","alienDescription":"A small, amphibious creature that glows in the dark and communicates through light pulses.","alienImage":"../img/alienImgs/a10.webp","alienSound":"../sound/10.wav"}
]